url: https://needleworm.github.io/
baseurl: /bhban_ai

# Site settings
title: 수학, 통계를 몰라도 이해할 수 있는 쉬운 딥러닝
email: bhban@kakao.com
description: 비전공자도 볼 수 있는 최초의 딥러닝 입문서


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/needleworm


# Build settings
highlighter: true
markdown: kramdown
permalink: pretty

