url: https://needleworm.github.io/
baseurl: /bhban_ai

# Site settings
title: 수학, 통계를 몰라도 이해할 수 있는 쉬운 딥러닝
email: bhban@kakao.com
description: 비전공자도 볼 수 있는 최초의 딥러닝 입문서


books:
- title: 돈이 복사되는 가상자산 수업
  pic: https://cdn.jsdelivr.net/gh/needleworm/needleworm.github.io/src/images/books/covers/14.jpg
  stores:
    - shop: naver
      url: #
    - shop: aladdin
      url: #
    - shop: yes24
      url: #
    - shop: kyobo
      url: #
      
- title: 142가지 데이터셋
  pic: https://cdn.jsdelivr.net/gh/needleworm/needleworm.github.io/src/images/books/covers/13.jpg
  stores:
    - shop: naver
      url: https://book.naver.com/bookdb/book_detail.nhn?bid=21508184
    - shop: aladdin
      url: https://www.aladin.co.kr/shop/wproduct.aspx?ISBN=8970505350&start=pnaver_02
    - shop: yes24
      url: http://www.yes24.com/Product/Goods/107036705
    - shop: kyobo
      url: http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&linkClass=&barcode=9788970505350

- title: HTML, CSS, 자바스크립트
  pic: https://cdn.jsdelivr.net/gh/needleworm/needleworm.github.io/src/images/books/covers/12.jpg
  stores:
    - shop: naver
      url: https://book.naver.com/bookdb/book_detail.nhn?bid=21499497
    - shop: aladdin
      url: https://www.aladin.co.kr/shop/wproduct.aspx?ISBN=8970505369&start=pnaver_02
    - shop: yes24
      url: http://www.yes24.com/Product/Goods/107010853
    - shop: kyobo
      url: http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&linkClass=&barcode=9788970505367

- title: 봄 여름 가을 겨울 그리고 봄
  pic: https://cdn.jsdelivr.net/gh/needleworm/needleworm.github.io/src/images/books/covers/11.jpeg
  stores:
    - shop: naver
      url: https://book.naver.com/bookdb/book_detail.naver?bid=21295784
    - shop: aladdin
      url: http://aladin.kr/p/l4o7A
    - shop: yes24
      url: http://www.yes24.com/Product/Goods/105138391
    - shop: kyobo
      url: http://pod.kyobobook.co.kr/podBook/podBookDetailView.ink?ejkGb=KOR&barcode=1400000474846

- title: 101가지 컴퓨터 활용팁
  pic: https://cdn.jsdelivr.net/gh/needleworm/needleworm.github.io/src/images/books/covers/10.jpg
  stores:
    - shop: naver
      url: https://book.naver.com/bookdb/book_detail.nhn?bid=20739091
    - shop: aladdin
      url: https://www.aladin.co.kr/shop/wproduct.aspx?ISBN=897050494X&start=pnaver_02
    - shop: yes24
      url: http://www.yes24.com/Product/Goods/102593399
    - shop: kyobo
      url: http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&linkClass=&barcode=9788970504940


- title: 내 자산 자동으로 관리하기
  pic: https://cdn.jsdelivr.net/gh/needleworm/needleworm.github.io/src/images/books/covers/9.jpg
  stores:
    - shop: naver
      url: https://book.naver.com/bookdb/book_detail.nhn?bid=20764734
    - shop: kyobo
      url: https://digital.kyobobook.co.kr/digital/ebook/ebookDetail.ink?LINK=NVE&category=001&barcode=480D210717470
    - shop: ridi
      url: https://ridibooks.com/books/4638000001

      
- title: 쉬운 딥러닝
  pic: https://cdn.jsdelivr.net/gh/needleworm/needleworm.github.io/src/images/books/covers/8.jpg
  stores:
    - shop: naver
      url: https://book.naver.com/bookdb/book_detail.nhn?bid=19007726
    - shop: aladdin
      url: https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=269891239
    - shop: yes24
      url: http://www.yes24.com/Product/Goods/99552196
    - shop: kyobo
      url: http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9788970504872&orderClick=LAG&Kc=

- title: 업무 자동화
  pic: https://cdn.jsdelivr.net/gh/needleworm/needleworm.github.io/src/images/books/covers/1.jpg
  stores:
    - shop: naver
      url: https://book.naver.com/bookdb/book_detail.nhn?bid=17665326
    - shop: aladdin
      url: https://www.aladin.co.kr/shop/wproduct.aspx?ISBN=8970504745&start=pnaver_02
    - shop: yes24
      url: http://www.yes24.com/Product/Goods/96360166
    - shop: kyobo
      url: http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&linkclassName=&barcode=9788970504742

- title: 코딩하는 공익
  pic: https://cdn.jsdelivr.net/gh/needleworm/needleworm.github.io/src/images/books/covers/7.jpg
  stores:
    - shop: naver
      url: https://book.naver.com/bookdb/book_detail.nhn?bid=16340073
    - shop: aladdin
      url: https://www.aladin.co.kr/shop/wproduct.aspx?ISBN=8955866119&start=pnaver_02
    - shop: yes24
      url: http://www.yes24.com/Product/Goods/90081924
    - shop: kyobo
      url: http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&linkClass=&barcode=9788955866117

- title: 공학자의 지혜묵상
  pic: https://cdn.jsdelivr.net/gh/needleworm/needleworm.github.io/src/images/books/covers/3.jpg
  stores:
    - shop: naver
      url: https://book.naver.com/bookdb/book_detail.nhn?bid=16369629
    - shop: aladdin
      url: https://www.aladin.co.kr/shop/wproduct.aspx?ISBN=K452639642&start=pnaver_02
    - shop: yes24
      url: http://www.yes24.com/Product/Goods/90392271
    - shop: kyobo
      url: http://pod.kyobobook.co.kr/podBook/podBookDetailView.ink?ejkGb=KOR&barcode=1400000378984

      
- title: 공학자의 오경묵상
  pic: https://cdn.jsdelivr.net/gh/needleworm/needleworm.github.io/src/images/books/covers/2.jpg
  stores:
    - shop: naver
      url: https://book.naver.com/bookdb/book_detail.nhn?bid=17469780
    - shop: aladdin
      url: https://www.aladin.co.kr/shop/wproduct.aspx?ISBN=K112735243&start=pnaver_02
    - shop: yes24
      url: http://www.yes24.com/Product/Goods/95590656
    - shop: kyobo
      url: http://pod.kyobobook.co.kr/podBook/podBookDetailView.ink?ejkGb=KOR&barcode=1400000403693

      
- title: 실전 민사소송법
  pic: https://cdn.jsdelivr.net/gh/needleworm/needleworm.github.io/src/images/books/covers/6.jpg
  stores:
    - shop: naver
      url: https://book.naver.com/bookdb/book_detail.nhn?bid=16357665
    - shop: aladdin
      url: https://www.aladin.co.kr/shop/wproduct.aspx?ISBN=K572639625&start=pnaver_02
    - shop: yes24
      url: http://www.yes24.com/Product/Goods/90250538
    - shop: kyobo
      url: http://pod.kyobobook.co.kr/podBook/podBookDetailView.ink?ejkGb=KOR&barcode=1400000377208

      
- title: 법대로 합시다
  pic: https://cdn.jsdelivr.net/gh/needleworm/needleworm.github.io/src/images/books/covers/5.jpg
  stores:
    - shop: naver
      url: https://book.naver.com/bookdb/book_detail.nhn?bid=10236421
    - shop: yes24
      url: http://www.yes24.com/Product/Goods/30660689
    - shop: kyobo
      url: http://digital.kyobobook.co.kr/digital/ebook/ebookDetail.ink?LINK=NVE&category=001&barcode=4801159610081

      
- title: 나는 아직 잊힐 준비가 되지 않았어요
  pic: https://cdn.jsdelivr.net/gh/needleworm/needleworm.github.io/src/images/books/covers/4.jpg
  stores:
    - shop: naver
      url: https://book.naver.com/bookdb/book_detail.nhn?bid=16629718
    - shop: aladdin
      url: https://www.aladin.co.kr/shop/wproduct.aspx?ISBN=K622632023&start=pnaver_02
    - shop: yes24
      url: http://www.yes24.com/Product/Goods/92154589
    - shop: kyobo
      url: http://pod.kyobobook.co.kr/podBook/podBookDetailView.ink?ejkGb=KOR&barcode=1400000388044

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/needleworm


# Build settings
highlighter: true
markdown: kramdown
permalink: pretty

